package main

import (
	"fmt"
	log "log/slog"
	"offline_modules/cmd"

	_ "github.com/AlecAivazis/survey/v2"
	_ "github.com/atotto/clipboard"
	_ "github.com/briandowns/spinner"
	_ "github.com/charmbracelet/bubbles/cursor"
	_ "github.com/charmbracelet/bubbles/filepicker"
	_ "github.com/charmbracelet/bubbles/help"
	_ "github.com/charmbracelet/bubbles/key"
	_ "github.com/charmbracelet/bubbles/list"
	_ "github.com/charmbracelet/bubbles/paginator"
	_ "github.com/charmbracelet/bubbles/progress"
	_ "github.com/charmbracelet/bubbles/runeutil"
	_ "github.com/charmbracelet/bubbles/spinner"
	_ "github.com/charmbracelet/bubbles/stopwatch"
	_ "github.com/charmbracelet/bubbles/table"
	_ "github.com/charmbracelet/bubbles/textarea"
	_ "github.com/charmbracelet/bubbles/textinput"
	_ "github.com/charmbracelet/bubbles/timer"
	_ "github.com/charmbracelet/bubbles/viewport"
	_ "github.com/charmbracelet/bubbletea"
	_ "github.com/charmbracelet/glamour"
	_ "github.com/charmbracelet/lipgloss"
	_ "github.com/chromedp/chromedp"
	_ "github.com/fatih/color"
	_ "github.com/gizak/termui/v3"
	_ "github.com/gizak/termui/v3/widgets"
	_ "github.com/gocolly/colly"
	_ "github.com/labstack/echo-contrib/session"
	_ "github.com/labstack/echo-jwt/v4"
	_ "github.com/labstack/echo/v4"
	_ "github.com/olekukonko/tablewriter"
	_ "github.com/playwright-community/playwright-go"
	_ "github.com/pocketbase/pocketbase/apis"
	_ "github.com/pocketbase/pocketbase/cmd"
	_ "github.com/pocketbase/pocketbase/core"
	_ "github.com/pocketbase/pocketbase/daos"
	_ "github.com/pocketbase/pocketbase/examples/base"
	_ "github.com/pocketbase/pocketbase/forms/validators"
	_ "github.com/pocketbase/pocketbase/mails/templates"
	_ "github.com/pocketbase/pocketbase/migrations/logs"
	_ "github.com/pocketbase/pocketbase/models/schema"
	_ "github.com/pocketbase/pocketbase/models/settings"
	_ "github.com/pocketbase/pocketbase/plugins/ghupdate"
	_ "github.com/pocketbase/pocketbase/plugins/jsvm"
	_ "github.com/pocketbase/pocketbase/plugins/migratecmd"
	_ "github.com/pocketbase/pocketbase/resolvers"
	_ "github.com/pocketbase/pocketbase/tests"
	_ "github.com/pocketbase/pocketbase/tokens"
	_ "github.com/pocketbase/pocketbase/tools/archive"
	_ "github.com/pocketbase/pocketbase/tools/auth"
	_ "github.com/pocketbase/pocketbase/tools/cron"
	_ "github.com/pocketbase/pocketbase/tools/dbutils"
	_ "github.com/pocketbase/pocketbase/tools/filesystem"
	_ "github.com/pocketbase/pocketbase/tools/hook"
	_ "github.com/pocketbase/pocketbase/tools/inflector"
	_ "github.com/pocketbase/pocketbase/tools/list"
	_ "github.com/pocketbase/pocketbase/tools/logger"
	_ "github.com/pocketbase/pocketbase/tools/mailer"
	_ "github.com/pocketbase/pocketbase/tools/migrate"
	_ "github.com/pocketbase/pocketbase/tools/osutils"
	_ "github.com/pocketbase/pocketbase/tools/rest"
	_ "github.com/pocketbase/pocketbase/tools/routine"
	_ "github.com/pocketbase/pocketbase/tools/search"
	_ "github.com/pocketbase/pocketbase/tools/security"
	_ "github.com/pocketbase/pocketbase/tools/store"
	_ "github.com/pocketbase/pocketbase/tools/subscriptions"
	_ "github.com/pocketbase/pocketbase/tools/template"
	_ "github.com/pocketbase/pocketbase/tools/tokenizer"
	_ "github.com/pocketbase/pocketbase/tools/types"
	_ "github.com/pocketbase/pocketbase/ui"
	_ "github.com/schollz/progressbar/v3"
	_ "github.com/sijms/go-ora/v2"
	_ "github.com/spf13/cobra"
	_ "github.com/spf13/viper"
	_ "github.com/stretchr/testify/assert"
	_ "github.com/stretchr/testify/mock"
	_ "github.com/stretchr/testify/require"
	_ "github.com/stretchr/testify/suite"
	_ "modernc.org/sqlite"
)

func main() {
	fmt.Println("문자열 출력")
	log.Info("로깅 출력")
	cmd.Playground()
}
